spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Recommend?serverTimezone=UTC
    username: root
    password: mysql
    hikari:
      minimum-idle: 3
  redis:
    host: localhost
    database: 0
    port: 6379
    connect-timeout: 10
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true